# Estos enlaces hacen aparecer el botón "Sponsor" en la página del repositorio.
# Docs: https://docs.github.com/es/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository
github: [jeyssonlza]
